//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaXwebService.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Peca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Peca()
        {
            this.OrdemDeServico = new HashSet<OrdemDeServico>();
        }
    
        public int id { get; set; }
        public string cod { get; set; }
        public byte[] desenho { get; set; }
        public Nullable<double> largura { get; set; }
        public Nullable<double> comprimento { get; set; }
        public Nullable<double> diametro { get; set; }
        public Nullable<int> materialId { get; set; }

        [JsonIgnore]
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<OrdemDeServico> OrdemDeServico { get; set; }
    }
}
