//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpresaXwebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usinagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usinagem()
        {
            this.OrdemDeServico = new HashSet<OrdemDeServico>();
            this.Realizado = new HashSet<Realizado>();
        }
    
        public int id { get; set; }
        public Nullable<double> pequeno { get; set; }
        public Nullable<double> medio { get; set; }
        public Nullable<double> grande { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdemDeServico> OrdemDeServico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realizado> Realizado { get; set; }
    }
}
